# Site settings
title: nyl.io
email: hi@nyl.io
description: "In order to be old and wise, you must first be young and stupid."
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://nyl.io" # the base hostname & protocol for your site
twitter_username: nliang
github_username:  neuralfirings
timezone: America/Los_Angeles
permalink: /:year/:month/:title

# Build settings
markdown: kramdown

# Dependencies (cp from other blog)
pygments:         true
permalink: /:year/:month/:title/
