# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
relative_permalinks: true
timezone: America/Los_Angeles
permalink: /:year/:month/:title

# Setup
title:               nyl.io
tagline:             'Random neural firings by Nancy Yi Liang.'
description:         ''
url:                 http://www.nyl.io/blog
baseurl:             '/blog'
paginate:            5

# About/contact
author:
  name:              Nancy Yi Liang
  url:               https://twitter.com/nliang
  email:             hi@nyl.io

# Custom vars
version:             1.0.0
